version: '3'
services:
  webpacker:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - '3035:3035'
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bin/webpack-dev-server"
    volumes:
      - .:/myapp
    working_dir: /myapp
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0 
  web:
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    ports:
      - "80:3000"
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - ./bundle-data:/usr/local/bundle
    depends_on:
      - webpacker
      - db
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: webpacker
  db:
    user: "1000:50"
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/volumes:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
