FROM ruby:2.5.1

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update -qq && apt-get install -y build-essential libpq-dev mysql-client nodejs yarn

ENV APP_HOME /myapp
WORKDIR $APP_HOME

RUN gem install bundler

ADD . $APP_HOME
RUN bundle config build.nokogiri --use-system-libraries
